let state = {
    sportClothesImg: [
        { id: 1, src: '/img_sportClothe/sport_clothes_1.jpg' },
        { id: 2, src: '/img_sportClothe/sport_clothes_2.jpg' },
        { id: 3, src: '/img_sportClothe/sport_clothes_3.jpg' },
        { id: 4, src: '/img_sportClothe/sport_clothes_4.jpg' },
        { id: 5, src: '/img_sportClothe/sport_clothes_5.jpg' },
        { id: 6, src: '/img_sportClothe/sport_clothes_6.jpg' },
        { id: 7, src: '/img_sportClothe/sport_clothes_7.jpg' },
        { id: 8, src: '/img_sportClothe/sport_clothes_8.jpg' },
        { id: 9, src: '/img_sportClothe/sport_clothes_9.jpg' },
        { id: 10, src: '/img_sportClothe/sport_clothes_10.jpg' },
        { id: 11, src: '/img_sportClothe/sport_clothes_11.jpg' },
        { id: 12, src: '/img_sportClothe/sport_clothes_12.jpg' },
        { id: 13, src: '/img_sportClothe/sport_clothes_13.jpg' },
        { id: 14, src: '/img_sportClothe/sport_clothes_14.jpg' },
        { id: 15, src: '/img_sportClothe/sport_clothes_15.jpg' },
        { id: 16, src: '/img_sportClothe/sport_clothes_16.jpg' }
    ],
    corporateClotheImg: [
        { id: 1, src: '/img_corporateClothe/corporate_clothing_1.jpg' },
        { id: 2, src: '/img_corporateClothe/corporate_clothing_2.jpg' },
        { id: 3, src: '/img_corporateClothe/corporate_clothing_3.jpg' },
        { id: 4, src: '/img_corporateClothe/corporate_clothing_4.jpg' },
        { id: 5, src: '/img_corporateClothe/corporate_clothing_5.jpg' },
        { id: 6, src: '/img_corporateClothe/corporate_clothing_6.jpg' },
        { id: 7, src: '/img_corporateClothe/corporate_clothing_7.jpg' },
        { id: 8, src: '/img_corporateClothe/corporate_clothing_8.jpg' },
        { id: 9, src: '/img_corporateClothe/corporate_clothing_9.jpg' },
        { id: 10, src: '/img_corporateClothe/corporate_clothing_10.jpg' },
        { id: 11, src: '/img_corporateClothe/corporate_clothing_11.jpg' }
    ],
    sportClothes: {
        sportTshirtMen: {
            img: [
                { src: '/img_modalWindows/tshirtMan.png' }
            ],
            colorChart: [
                { id: 1, size: '30', bgcolor: 'none', color: '#000000', border: '1px solid black'},
                { id: 2, size: '34', bgcolor: '#FFC709', color: '#000000' },
                { id: 3, size: '36', bgcolor: '#181A1C', color: '#FFFFFF' },
                { id: 4, size: '40', bgcolor: '#ED1A38', color: '#FFFFFF' },
                { id: 5, size: '44', bgcolor: '#F36C21', color: '#FFFFFF' },
                { id: 6, size: '47', bgcolor: '#00A963', color: '#FFFFFF' },
                { id: 7, size: '51', bgcolor: '#1763AF', color: '#FFFFFF' },
                { id: 8, size: '57', bgcolor: '#EF447D', color: '#FFFFFF' },
                { id: 9, size: '94', bgcolor: '#BEC4C9', color: '#000000' },
                { id: 10, size: 'AZ', bgcolor: '#00093C', color: '#FFFFFF' },
                { id: 11, size: 'K2', bgcolor: '#FFF200', color: '#000000' },
                { id: 12, size: '41', bgcolor: '#6A1B42', color: '#FFFFFF' },
                { id: 13, size: 'ZU', bgcolor: '#007CB1', color: '#FFFFFF' },
                { id: 14, size: '32', bgcolor: '#002A5C', color: '#FFFFFF' },
                { id: 15, size: 'XW', bgcolor: '#A2ACAB', color: '#000000' },
                { id: 16, size: 'GL', bgcolor: '#424444', color: '#FFFFFF' },
                { id: 17, size: 'LM', bgcolor: '#7AC143', color: '#FFFFFF' }
            ],
            sizeChart: [
                { id: 1, size: '', weight: '' },
                { id: 2, size: 'A', weight: 'bold' },
                { id: 3, size: 'B', weight: 'bold' },
                { id: 4, size: 'вага, кг', weight: 'bold', text: 'lowercase' },
                { id: 5, size: 'S', weight: 'bold' },
                { id: 6, size: '48', weight: 'normal' },
                { id: 7, size: '69', weight: 'normal' },
                { id: 8, size: '60-65', weight: 'normal' },
                { id: 9, size: 'M', weight: 'bold' },
                { id: 10, size: '53', weight: 'normal' },
                { id: 11, size: '72', weight: 'normal' },
                { id: 12, size: '76-85', weight: 'normal' },
                { id: 13, size: 'L', weight: 'bold' },
                { id: 14, size: '56', weight: 'normal' },
                { id: 15, size: '74', weight: 'normal' },
                { id: 16, size: '86-92', weight: 'normal' },
                { id: 17, size: 'XL', weight: 'bold' },
                { id: 18, size: '61', weight: 'normal' },
                { id: 19, size: '77', weight: 'normal' },
                { id: 20, size: '93-99', weight: 'normal' },
                { id: 21, size: '2XL', weight: 'bold' },
                { id: 22, size: '66', weight: 'normal' },
                { id: 23, size: '78', weight: 'normal' },
                { id: 24, size: '100-110', weight: 'normal' }
            ]
        },
    sportTshirtPoloMen: {
            img: [
                { src: '/img_modalWindows/tshirtManPolo.png' }
            ],
            colorChart: [
                { id: 1, size: '30', bgcolor: 'none', color: '#000000', border: '1px solid black' },
                { id: 2, size: '34', bgcolor: '#FFC709', color: '#000000' },
                { id: 3, size: '36', bgcolor: '#181A1C', color: '#FFFFFF' },
                { id: 4, size: '40', bgcolor: '#ED1A38', color: '#FFFFFF' },
                { id: 5, size: '44', bgcolor: '#F36C21', color: '#FFFFFF' },
                { id: 6, size: '47', bgcolor: '#00A963', color: '#FFFFFF' },
                { id: 7, size: '51', bgcolor: '#1763AF', color: '#FFFFFF' },
                { id: 8, size: '94', bgcolor: '#EF447D', color: '#FFFFFF' },
                { id: 9, size: 'AZ', bgcolor: '#BEC4C9', color: '#000000' },
                { id: 10, size: '41', bgcolor: '#00093C', color: '#FFFFFF' },
                { id: 11, size: '77', bgcolor: '#FFF200', color: '#000000' },
                { id: 12, size: '38', bgcolor: '#6A1B42', color: '#FFFFFF' },
                { id: 13, size: 'YT', bgcolor: '#007CB1', color: '#FFFFFF' },
                { id: 14, size: 'PE', bgcolor: '#002A5C', color: '#FFFFFF' },
                { id: 15, size: '32', bgcolor: '#A2ACAB', color: '#000000' }
            ],
            sizeChart: [
                { id: 1, size: '', weight: '' },
                { id: 2, size: 'A', weight: 'bold' },
                { id: 3, size: 'B', weight: 'bold' },
                { id: 4, size: 'вага, кг', weight: 'bold', text: 'lowercase' },
                { id: 5, size: 'S', weight: 'bold' },
                { id: 6, size: '48', weight: 'normal' },
                { id: 7, size: '70', weight: 'normal' },
                { id: 8, size: '60-65', weight: 'normal' },
                { id: 9, size: 'M', weight: 'bold' },
                { id: 10, size: '52', weight: 'normal' },
                { id: 11, size: '72', weight: 'normal' },
                { id: 12, size: '76-85', weight: 'normal' },
                { id: 13, size: 'L', weight: 'bold' },
                { id: 14, size: '56', weight: 'normal' },
                { id: 15, size: '74', weight: 'normal' },
                { id: 16, size: '86-92', weight: 'normal' },
                { id: 17, size: 'XL', weight: 'bold' },
                { id: 18, size: '60', weight: 'normal' },
                { id: 19, size: '76', weight: 'normal' },
                { id: 20, size: '93-99', weight: 'normal' },
                { id: 21, size: '2XL', weight: 'bold' },
                { id: 22, size: '64', weight: 'normal' },
                { id: 23, size: '78', weight: 'normal' },
                { id: 24, size: '100-110', weight: 'normal' }
            ]
        },
        sportTshirtWoman: {
            img: [
                { src: '/img_modalWindows/tshirtWomanImg.png' }
            ],
            colorChart: [
                { id: 1, size: '30', bgcolor: 'none', color: '#000000', border: '1px solid black' },
                { id: 2, size: '34', bgcolor: '#FFC709', color: '#000000' },
                { id: 3, size: '36', bgcolor: '#181A1C', color: '#FFFFFF' },
                { id: 4, size: '40', bgcolor: '#ED1A38', color: '#FFFFFF' },
                { id: 5, size: '44', bgcolor: '#F36C21', color: '#FFFFFF' },
                { id: 6, size: '47', bgcolor: '#00A963', color: '#FFFFFF' },
                { id: 7, size: '51', bgcolor: '#1763AF', color: '#FFFFFF' },
                { id: 8, size: '57', bgcolor: '#EF447D', color: '#FFFFFF' },
                { id: 9, size: '94', bgcolor: '#BEC4C9', color: '#000000' },
                { id: 10, size: 'AZ', bgcolor: '#00093C', color: '#FFFFFF' },
                { id: 11, size: 'K2', bgcolor: '#FFF200', color: '#000000' },
                { id: 12, size: '41', bgcolor: '#6A1B42', color: '#FFFFFF' },
                { id: 13, size: 'ZU', bgcolor: '#007CB1', color: '#FFFFFF' },
                { id: 14, size: '32', bgcolor: '#002A5C', color: '#FFFFFF' },
                { id: 15, size: 'XW', bgcolor: '#A2ACAB', color: '#000000' },
                { id: 16, size: 'GL', bgcolor: '#424444', color: '#FFFFFF' },
                { id: 17, size: 'LM', bgcolor: '#7AC143', color: '#FFFFFF' }
            ],
            sizeChart: [
                { id: 1, size: '', weight: '' },
                { id: 2, size: 'A', weight: 'bold' },
                { id: 3, size: 'B', weight: 'bold' },
                { id: 4, size: 'вага, кг', weight: 'bold', text: 'lowercase' },
                { id: 5, size: 'XS', weight: 'bold' },
                { id: 6, size: '41', weight: 'normal' },
                { id: 7, size: '63', weight: 'normal' },
                { id: 8, size: '45-53', weight: 'normal' },
                { id: 9, size: 'S', weight: 'bold' },
                { id: 10, size: '44', weight: 'normal' },
                { id: 11, size: '64', weight: 'normal' },
                { id: 12, size: '54-58', weight: 'normal' },
                { id: 13, size: 'M', weight: 'bold' },
                { id: 14, size: '46', weight: 'normal' },
                { id: 15, size: '65', weight: 'normal' },
                { id: 16, size: '59-65', weight: 'normal' },
                { id: 17, size: 'L', weight: 'bold' },
                { id: 18, size: '49', weight: 'normal' },
                { id: 19, size: '66', weight: 'normal' },
                { id: 20, size: '66-74', weight: 'normal' },
                { id: 21, size: 'XL', weight: 'bold' },
                { id: 22, size: '51', weight: 'normal' },
                { id: 23, size: '67', weight: 'normal' },
                { id: 24, size: '75-84', weight: 'normal'},
                { id: 21, size: '2XL', weight: 'bold' },
                { id: 22, size: '54', weight: 'normal' },
                { id: 23, size: '68', weight: 'normal' },
                { id: 24, size: '85+', weight: 'normal'}
            ]
        },
        sportTshirtPoloWoman: {
            img: [
                { src: '/img_modalWindows/tshirtPoloWoman.png' }
            ],
            colorChart: [
                { id: 1, size: '30', bgcolor: 'none', color: '#000000', border: '1px solid black' },
                { id: 2, size: '34', bgcolor: '#FFC709', color: '#000000' },
                { id: 3, size: '36', bgcolor: '#181A1C', color: '#FFFFFF' },
                { id: 4, size: '40', bgcolor: '#ED1A38', color: '#FFFFFF' },
                { id: 5, size: '44', bgcolor: '#F36C21', color: '#FFFFFF' },
                { id: 6, size: '47', bgcolor: '#00A963', color: '#FFFFFF' },
                { id: 7, size: '51', bgcolor: '#1763AF', color: '#FFFFFF' },
                { id: 8, size: '94', bgcolor: '#EF447D', color: '#FFFFFF' },
                { id: 9, size: 'AZ', bgcolor: '#BEC4C9', color: '#000000' },
                { id: 10, size: '41', bgcolor: '#00093C', color: '#FFFFFF' },
                { id: 11, size: '77', bgcolor: '#FFF200', color: '#000000' },
                { id: 12, size: '38', bgcolor: '#6A1B42', color: '#FFFFFF' },
                { id: 13, size: 'YT', bgcolor: '#007CB1', color: '#FFFFFF' },
                { id: 14, size: 'PE', bgcolor: '#002A5C', color: '#FFFFFF' },
                { id: 15, size: '32', bgcolor: '#A2ACAB', color: '#000000' }
            ],
            sizeChart: [
                { id: 1, size: '', weight: '' },
                { id: 2, size: 'A', weight: 'bold' },
                { id: 3, size: 'B', weight: 'bold' },
                { id: 4, size: 'вага, кг', weight: 'bold', text: 'lowercase' },
                { id: 5, size: 'XS', weight: 'bold' },
                { id: 6, size: '42', weight: 'normal' },
                { id: 7, size: '61', weight: 'normal' },
                { id: 8, size: '45-53', weight: 'normal' },
                { id: 9, size: 'S', weight: 'bold' },
                { id: 10, size: '44', weight: 'normal' },
                { id: 11, size: '62', weight: 'normal' },
                { id: 12, size: '54-58', weight: 'normal' },
                { id: 13, size: 'M', weight: 'bold' },
                { id: 14, size: '47', weight: 'normal' },
                { id: 15, size: '63', weight: 'normal' },
                { id: 16, size: '59-65', weight: 'normal' },
                { id: 17, size: 'L', weight: 'bold' },
                { id: 18, size: '49', weight: 'normal' },
                { id: 19, size: '64', weight: 'normal' },
                { id: 20, size: '66-74', weight: 'normal' },
                { id: 21, size: 'XL', weight: 'bold' },
                { id: 22, size: '52', weight: 'normal' },
                { id: 23, size: '65', weight: 'normal' },
                { id: 24, size: '75-84', weight: 'normal' },
                { id: 21, size: '2XL', weight: 'bold' },
                { id: 22, size: '54', weight: 'normal' },
                { id: 23, size: '66', weight: 'normal' },
                { id: 24, size: '85+', weight: 'normal' }
            ]
        },
        hoodietMen: {
            img: [
                { src: '/img_modalWindows/hoodieMen.png' }
            ],
            colorChart: [
                { id: 1, size: '30', bgcolor: 'none', color: '#000000', border: '1px solid black' },
                { id: 2, size: '36', bgcolor: '#0A0A0D', color: '#FFFFFF' },
                { id: 3, size: '40', bgcolor: '#FB1227', color: '#FFFFFF' },
                { id: 4, size: '47', bgcolor: '#229C54', color: '#FFFFFF' },
                { id: 5, size: '51', bgcolor: '#26489E', color: '#FFFFFF' },
                { id: 6, size: '94', bgcolor: '#B3B7B4', color: '#FFFFFF' },
                { id: 7, size: 'AZ', bgcolor: '#04081C', color: '#FFFFFF' },
                { id: 8, size: 'HD', bgcolor: '#14181E', color: '#FFFFFF' },
                { id: 9, size: '41', bgcolor: '#4E082F', color: '#FFFFFF' },
                { id: 10, size: '77', bgcolor: '#106C5F', color: '#FFFFFF' },
                { id: 11, size: '59', bgcolor: '#4A4E39', color: '#FFFFFF' },
                { id: 12, size: '38', bgcolor: '#102A1B', color: '#FFFFFF' },
                { id: 13, size: 'PE', bgcolor: '#1F006C', color: '#FFFFFF' },
                { id: 14, size: '32', bgcolor: '#061238', color: '#FFFFFF' }
            ],
            sizeChart: [
                { id: 1, size: '', weight: '' },
                { id: 2, size: 'A', weight: 'bold' },
                { id: 3, size: 'B', weight: 'bold' },
                { id: 4, size: 'вага, кг', weight: 'bold', text: 'lowercase' },
                { id: 5, size: 'S', weight: 'bold' },
                { id: 6, size: '51', weight: 'normal' },
                { id: 7, size: '67', weight: 'normal' },
                { id: 8, size: '60-65', weight: 'normal' },
                { id: 9, size: 'M', weight: 'bold' },
                { id: 10, size: '56', weight: 'normal' },
                { id: 11, size: '70', weight: 'normal' },
                { id: 12, size: '76-85', weight: 'normal' },
                { id: 13, size: 'L', weight: 'bold' },
                { id: 14, size: '61', weight: 'normal' },
                { id: 15, size: '73', weight: 'normal' },
                { id: 16, size: '86-92', weight: 'normal' },
                { id: 17, size: 'XL', weight: 'bold' },
                { id: 18, size: '63', weight: 'normal' },
                { id: 19, size: '76', weight: 'normal' },
                { id: 20, size: '93-99', weight: 'normal' },
                { id: 21, size: '2XL', weight: 'bold' },
                { id: 22, size: '68', weight: 'normal' },
                { id: 23, size: '79', weight: 'normal' },
                { id: 24, size: '100-110', weight: 'normal' }
            ]
        },
        hoodietWoman: {
            img: [
                { src: '/img_modalWindows/hoodieWoman.png.png' }
            ],
            colorChart: [
                { id: 1, size: '30', bgcolor: 'none', color: '#000000', border: '1px solid black' },
                { id: 2, size: '36', bgcolor: '#0A0A0D', color: '#FFFFFF' },
                { id: 3, size: '40', bgcolor: '#FB1227', color: '#FFFFFF' },
                { id: 4, size: '44', bgcolor: '#FE5311', color: '#FFFFFF' },
                { id: 5, size: '47', bgcolor: '#229C54', color: '#FFFFFF' },
                { id: 6, size: '51', bgcolor: '#26489E', color: '#FFFFFF' },
                { id: 7, size: '57', bgcolor: '#F52D74', color: '#FFFFFF' },
                { id: 8, size: '94', bgcolor: '#B3B7B4', color: '#FFFFFF' },
                { id: 9, size: 'AZ', bgcolor: '#04081C', color: '#FFFFFF' },
                { id: 10, size: '41', bgcolor: '#4E082F', color: '#FFFFFF' },
                { id: 11, size: '38', bgcolor: '#102A1B', color: '#FFFFFF' },
                { id: 12, size: 'ZU', bgcolor: '#066B96', color: '#FFFFFF' },
                { id: 13, size: 'PE', bgcolor: '#1F006C', color: '#FFFFFF' },
                { id: 14, size: 'GL', bgcolor: '#2A2729', color: '#FFFFFF' }
            ],
            sizeChart: [
                { id: 1, size: '', weight: '' },
                { id: 2, size: 'A', weight: 'bold' },
                { id: 3, size: 'B', weight: 'bold' },
                { id: 4, size: 'вага, кг', weight: 'bold', text: 'lowercase' },
                { id: 5, size: 'XS', weight: 'bold' },
                { id: 6, size: '46', weight: 'normal' },
                { id: 7, size: '62', weight: 'normal' },
                { id: 8, size: '45-53', weight: 'normal' },
                { id: 9, size: 'S', weight: 'bold' },
                { id: 10, size: '48', weight: 'normal' },
                { id: 11, size: '63', weight: 'normal' },
                { id: 12, size: '54-58', weight: 'normal' },
                { id: 13, size: 'M', weight: 'bold' },
                { id: 14, size: '51', weight: 'normal' },
                { id: 15, size: '65', weight: 'normal' },
                { id: 16, size: '59-65', weight: 'normal' },
                { id: 17, size: 'L', weight: 'bold' },
                { id: 18, size: '53', weight: 'normal' },
                { id: 19, size: '66', weight: 'normal' },
                { id: 20, size: '66-74', weight: 'normal' },
                { id: 21, size: 'XL', weight: 'bold' },
                { id: 22, size: '56', weight: 'normal' },
                { id: 23, size: '68', weight: 'normal' },
                { id: 24, size: '75-84', weight: 'normal' },
                { id: 21, size: '2XL', weight: 'bold' },
                { id: 22, size: '58', weight: 'normal' },
                { id: 23, size: '69', weight: 'normal' },
                { id: 24, size: '85+', weight: 'normal' }
            ]
        }
    },
    ourWorks: [
        { id: 1, src: '/img_ourWorks/img_main_works1.jpg' },
        { id: 2, src: '/img_ourWorks/img_main_works2.jpg' },
        { id: 3, src: '/img_ourWorks/img_main_works3.jpg' },
        { id: 4, src: '/img_ourWorks/img_main_works4.jpg' },
        { id: 5, src: '/img_ourWorks/img_main_works5.jpg' },
        { id: 6, src: '/img_ourWorks/img_main_works6.jpg' }
        
    ],

    sliderPhoto: [
        { id: 1, src: '/img_mainPage/img_main_works1.jpg' },
        { id: 2, src: '/img_mainPage/img_main_works2.jpg' },
        { id: 3, src: '/img_mainPage/img_main_works3.jpg' },
        { id: 4, src: '/img_mainPage/img_main_works4.jpg' },
        { id: 5, src: '/img_mainPage/img_main_works5.jpg' },
        { id: 6, src: '/img_mainPage/img_main_works6.jpg' }
    ]
};


export default state;

